#!/bin/sh -e

case "$1" in
	configure)
		# see below
		killall gnome-panel
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac
