#!/bin/sh -e
#DEBHELPER#

case "$1" in
	configure)
		# see below
		# killall gnome-panel
		kill -1 `ps ax | awk '{if ($5 == "gnome-panel") print $1;}'`
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac
